"""Typed, deterministic presentation contract for Replay read models."""
from __future__ import annotations
from dataclasses import dataclass
from enum import StrEnum
from html import escape
from typing import Mapping
from .dashboard_read_model import REPLAY_DASHBOARD_READ_MODEL_VERSION, ReplayDashboardReadModel
from .comparison import REPLAY_FRAME_COMPARISON_VERSION

REPLAY_PRESENTER_VERSION="1.0"
class ReplayPresenterSectionKey(StrEnum): STATUS_BANNER="status_banner"; HEADER="header"; HERO="replay_hero"; PROGRESS="replay_progress"; DECISION="decision_summary"; COMPARISON="frame_comparison"; TIMEFRAMES="timeframe_cards"; MODULES="module_cards"; MESSAGES="messages"; FOOTER="footer"
class ReplayPresenterThemeState(StrEnum): NORMAL="normal"; CALM="calm"; CHANGED="changed"; WAITING="waiting"; CAUTION="caution"; DANGER="danger"; UNAVAILABLE="unavailable"
@dataclass(frozen=True,slots=True)
class ReplayPresenterConfig:
 supported_read_model_versions:frozenset[str]=frozenset({REPLAY_DASHBOARD_READ_MODEL_VERSION}); supported_comparison_versions:frozenset[str]=frozenset({REPLAY_FRAME_COMPARISON_VERSION}); presenter_version:str=REPLAY_PRESENTER_VERSION; section_order:tuple[ReplayPresenterSectionKey,...]=tuple(ReplayPresenterSectionKey); timeframe_order:tuple[str,...]=("15m","60m","1d","1w"); module_order:tuple[str,...]=("position","trend","structure","timing"); warning_limit:int=32; message_limit:int=8; changed_field_limit:int=8; show_source_versions:bool=True; show_raw_hashes:bool=False; show_lineage:bool=False; html_escape:bool=True; language:str="zh-TW"; page_title:str="KAM Trade V3 Replay"; page_subtitle:str="Trading Decision Replay System"; development_mode:bool=False
 def __post_init__(self):
  if self.presenter_version!=REPLAY_PRESENTER_VERSION or self.section_order!=tuple(ReplayPresenterSectionKey) or self.timeframe_order!=("15m","60m","1d","1w") or self.module_order!=("position","trend","structure","timing") or min(self.warning_limit,self.message_limit,self.changed_field_limit)<=0 or self.language!="zh-TW": raise ValueError("Invalid Replay presenter config")
@dataclass(frozen=True,slots=True)
class ReplayPresenterView:
 presenter_version:str; source_read_model_version:str; source_comparison_version:str; scenario_id:str; run_id:str; frame_id:str; frame_sequence:int; page_title:str; page_subtitle:str; display_state:str; attention_level:str; theme_state:ReplayPresenterThemeState; section_order:tuple[str,...]; header:Mapping[str,object]; status_banner:Mapping[str,object]; hero:Mapping[str,object]; progress:Mapping[str,object]; decision:Mapping[str,object]; timeframe_cards:tuple[Mapping[str,object],...]; module_cards:tuple[Mapping[str,object],...]; comparison_summary:Mapping[str,object]; messages:tuple[Mapping[str,object],...]; footer:Mapping[str,object]; accessibility:Mapping[str,object]; valid:bool; warnings:tuple[str,...]; error_codes:tuple[str,...]
def _text(value,config):
 text="無法取得" if value is None else str(getattr(value,"value",value)); return escape(text,quote=True) if config.html_escape else text
def _score(value): return "無法取得" if value is None else (f"{value:.0f}" if hasattr(value,"__float__") and float(value).is_integer() else str(value))
def _theme(model):
 state=model.display_state.value; comparison=model.comparison.comparison_state.value
 return ReplayPresenterThemeState.UNAVAILABLE if state in {"invalid","unavailable"} else ReplayPresenterThemeState.DANGER if state=="blocked" else ReplayPresenterThemeState.CAUTION if state=="stale" else ReplayPresenterThemeState.CHANGED if comparison in {"changed","partially_changed"} else ReplayPresenterThemeState.CALM if comparison=="unchanged" else ReplayPresenterThemeState.NORMAL
def _invalid(config,code):
 cards=tuple({"timeframe":x,"display_label":x,"card_id":f"replay-timeframe-{x}","state_text":"無法取得","state_class":"replay-unavailable","direction_text":"unavailable","confidence_score_text":"無法取得","risk_score_text":"無法取得","next_step_text":"無法取得","valid":False,"aria_label":f"{x} 無法取得"} for x in config.timeframe_order); modules=tuple({"module":x,"display_title":x.title(),"card_id":f"replay-module-{x}","current_state_text":"無法取得","valid":False,"aria_label":f"{x} 無法取得"} for x in config.module_order); access={"language":"zh-TW","page_landmark_label":"Replay 回放","hero_aria_label":"回放摘要","progress_aria_label":"回放進度","decision_group_label":"決策摘要","comparison_group_label":"幀比較","timeframe_group_label":"週期卡片","module_group_label":"模組卡片","message_region_label":"訊息","status_live_mode":"assertive","heading_order_valid":True,"single_h1_required":True,"skip_link_target":"replay-main"}; return ReplayPresenterView(REPLAY_PRESENTER_VERSION,"","","","","",0,config.page_title,config.page_subtitle,"unavailable","unavailable",ReplayPresenterThemeState.UNAVAILABLE,tuple(x.value for x in config.section_order),{"title":config.page_title},{"visible":True,"severity":"critical","title":"回放資料無法顯示","aria_live":"assertive","dismissible":False},{"headline":"目前幀無法安全顯示決策","valid":False},{"percent_text":"無法取得","valid":False},{"direction_text":"unavailable","confidence_score_text":"無法取得","risk_score_text":"無法取得","next_step_text":"無法取得","valid":False},cards,modules,{"comparison_state":"invalid","headline":"比較資料無效","valid":False},({"severity":"critical","code":code,"title":"回放資料無法顯示","short_text":"資料不完整","aria_live":"assertive"},),{"product_name":"KAM Trade V3 Replay","disclaimer_text":"本頁僅供決策規則回放與研究，不構成交易建議。","valid":False},access,False,(),(code,))
def build_replay_presenter(model:ReplayDashboardReadModel,config:ReplayPresenterConfig)->ReplayPresenterView:
 if not isinstance(config,ReplayPresenterConfig): raise TypeError("ReplayPresenterConfig required")
 if not isinstance(model,ReplayDashboardReadModel): return _invalid(config,"input_type_mismatch")
 try:
  if model.read_model_version not in config.supported_read_model_versions or model.comparison_version not in config.supported_comparison_versions or len(model.timeframe_cards)!=4 or len(model.module_cards)!=4: return _invalid(config,"source_version_or_shape_mismatch")
  theme=_theme(model); state=model.display_state.value; attention=model.attention_level.value; comp=model.comparison; ds=model.decision_summary
  banner_needed=state!="ready"; banner={"visible":banner_needed,"severity":"critical" if state in {"invalid","blocked"} else "warning" if banner_needed else "info","title":"回放狀態","short_text":_text(state,config),"source_text":"read_model","frame_text":f"第 {model.frame_sequence} 幀","state_class":f"replay-{state}","aria_live":"assertive" if state in {"invalid","blocked"} else "polite","dismissible":False,"valid":model.valid}
  header={"title":config.page_title,"subtitle":config.page_subtitle,"product_name":"KAM Trade V3 Replay","product_type":"Trading Decision Replay System","scenario_label":_text(model.scenario_id,config),"frame_label":f"第 {model.frame_sequence} 幀","frame_sequence_text":str(model.frame_sequence),"event_type_text":_text(model.replay_state,config),"occurred_at_text":_text(model.occurred_at,config),"evaluated_at_text":_text(model.evaluated_at,config),"display_state_text":_text(state,config),"attention_text":_text(attention,config),"badge_text":"測試情境","badge_class":f"replay-{state}","development_fixture":config.development_mode,"valid":model.valid}
  progress={"current_index_text":str(model.replay_progress.current_index),"sequence_text":str(model.frame_sequence),"total_frames_text":str(model.total_frames),"percent_text":f"{model.replay_progress.progress_percent}%","progress_value":model.replay_progress.progress_percent,"progress_min":0,"progress_max":100,"is_first":model.replay_progress.is_first,"is_last":model.replay_progress.is_last,"previous_available":comp.previous_available,"next_available":model.next_frame_id is not None,"previous_frame_id":model.previous_frame_id,"next_frame_id":model.next_frame_id,"source_event_type_text":_text(model.replay_progress.source_event_type,config),"source_event_sequence_text":str(model.replay_progress.source_event_sequence),"aria_label":f"回放進度 {model.replay_progress.progress_percent}%","valid":model.valid}
  decision={"direction_label":"方向","direction_text":_text(ds.direction,config),"direction_class":f"direction-{_text(ds.direction,config)}","direction_change_text":_text(comp.direction_change.change_type,config),"confidence_label":"信心","confidence_text":_text(ds.confidence_state,config),"confidence_score_text":_score(ds.confidence),"confidence_class":"state-neutral","confidence_change_text":_text(comp.confidence_change.change_type,config),"risk_label":"風險","risk_text":_text(ds.risk_state,config),"risk_score_text":_score(ds.risk),"risk_class":"risk-state","risk_change_text":_text(comp.risk_change.change_type,config),"next_step_label":"下一步","next_step_text":_text(ds.next_step,config),"next_step_class":"state-neutral","next_step_change_text":_text(comp.next_step_change.change_type,config),"evaluated_text":"已評估" if ds.evaluated else "無法取得","valid":ds.valid,"warnings":ds.warnings,"error_codes":ds.error_codes}
  cards=tuple({"timeframe":c.timeframe.value,"display_label":c.timeframe.value,"card_id":f"replay-timeframe-{c.timeframe.value}","state_text":_text(c.current_state,config),"state_class":f"replay-{state}","update_state_text":_text(c.update_state,config),"candle_state_text":_text(c.candle_state,config),"market_data_state_text":_text(c.market_data_state,config),"direction_text":_text(c.direction,config),"direction_class":f"direction-{_text(c.direction,config)}","confidence_text":"信心","confidence_score_text":_score(c.confidence),"risk_text":"風險","risk_score_text":_score(c.risk),"next_step_text":_text(c.next_step,config),"change_text":_text(c.change_type,config),"change_class":f"change-{c.change_type}","inherited_text":"承接資料" if c.inherited else "","inherited":c.inherited,"stale":c.stale,"unavailable":c.unavailable,"valid":c.valid,"warning_texts":c.warnings,"aria_label":f"{c.timeframe.value} 狀態 {_text(c.current_state,config)}"} for c in model.timeframe_cards)
  questions={"position":"價格位置判斷有何變化？","trend":"趨勢線狀態有何變化？","structure":"市場結構有何變化？","timing":"確認狀態有何變化？"}; modules=tuple({"module":m.module,"display_title":m.module.title(),"card_id":f"replay-module-{m.module}","question_text":questions[m.module],"current_state_text":m.current_state,"previous_state_text":m.previous_state or "","changed_text":m.change_type,"change_class":f"change-{m.change_type}","evaluated_slot_count_text":str(m.evaluated_slot_count),"valid_slot_count_text":str(m.valid_slot_count),"unavailable_slot_count_text":str(m.unavailable_slot_count),"stale_slot_count_text":str(m.stale_slot_count),"invalid_slot_count_text":str(m.invalid_slot_count),"summary_text":m.summary,"attention_text":attention,"attention_class":f"attention-{attention}","warning_texts":m.warnings,"aria_label":f"{m.module} {m.current_state}","valid":m.valid} for m in model.module_cards)
  comparison={"comparison_state":comp.comparison_state.value,"comparison_state_text":_text(comp.comparison_state,config),"comparison_class":f"replay-{comp.comparison_state.value}","previous_frame_text":_text(comp.previous_frame_id,config),"current_frame_text":_text(comp.current_frame_id,config),"headline":"初始幀，尚無前一幀可比較" if comp.comparison_state.value=="initial" else "幀狀態比較","change_count_text":str(comp.change_count),"direction_change_text":_text(comp.direction_change.change_type,config),"confidence_change_text":_text(comp.confidence_change.change_type,config),"risk_change_text":_text(comp.risk_change.change_type,config),"next_step_change_text":_text(comp.next_step_change.change_type,config),"attention_change_text":_text(comp.attention_change.change_type,config),"validity_change_text":_text(comp.validity_change.change_type,config),"timeframe_change_count_text":str(sum(x.update_state_change.changed for x in comp.timeframe_changes)),"module_change_count_text":str(sum(x.change_type=="changed" for x in comp.module_changes)),"changed_field_texts":tuple(comp.changed_fields[:config.changed_field_limit]),"no_change_text":"無變化" if not comp.changed_fields else "","aria_label":"幀比較","valid":comp.valid,"warnings":comp.warnings,"error_codes":comp.error_codes}
  messages=tuple({"severity":"warning" if code!="no_change" else "info","code":code,"title":"回放訊息","short_text":_text(code,config),"source_text":"comparison","timeframe_text":"","module_text":"","frame_text":str(model.frame_sequence),"state_class":f"replay-{state}","detail_available":False,"aria_live":"polite"} for code in model.messages[:config.message_limit]); accessibility={"language":"zh-TW","page_landmark_label":"Replay 回放","hero_aria_label":"回放摘要","progress_aria_label":progress["aria_label"],"decision_group_label":"決策摘要","comparison_group_label":"幀比較","timeframe_group_label":"週期卡片","module_group_label":"模組卡片","message_region_label":"訊息","status_live_mode":banner["aria_live"],"heading_order_valid":True,"single_h1_required":True,"skip_link_target":"replay-main"}; footer={"product_name":"KAM Trade V3 Replay","product_type":"Trading Decision Replay System","scenario_id_text":_text(model.scenario_id,config),"run_id_text":_text(model.run_id,config),"frame_id_text":_text(model.frame_id,config),"evaluated_at_text":_text(model.evaluated_at,config),"replay_read_model_version":model.read_model_version,"comparison_version":model.comparison_version,"presenter_version":REPLAY_PRESENTER_VERSION,"fixture_label":"測試情境","development_label":"開發資料" if config.development_mode else "","disclaimer_text":"本頁僅供決策規則回放與研究，不構成交易建議。","valid":model.valid}
  return ReplayPresenterView(REPLAY_PRESENTER_VERSION,model.read_model_version,model.comparison_version,model.scenario_id,model.run_id,model.frame_id,model.frame_sequence,config.page_title,config.page_subtitle,state,attention,theme,tuple(x.value for x in config.section_order),header,banner,{"headline":f"第 {model.frame_sequence}／{model.total_frames} 幀","direction_text":_text(ds.direction,config),"confidence_score_text":_score(ds.confidence),"risk_score_text":_score(ds.risk),"next_step_text":_text(ds.next_step,config),"valid":model.valid},progress,decision,cards,modules,comparison,messages,footer,accessibility,model.valid,model.warnings,model.error_codes)
 except Exception: return _invalid(config,"presenter_mapping_failed")
