"""Fixed, escaped HTML contract for read-only Replay pages."""
from __future__ import annotations
from html import escape
from .wsgi_adapter import REPLAY_UI_VERSION, ReplayWSGIContext
def render_replay_ui(context:ReplayWSGIContext)->str:
 if not isinstance(context,ReplayWSGIContext): raise TypeError("ReplayWSGIContext required")
 e=lambda v:escape(str(v),quote=True)
 cards=''.join(f'<article id="{e(c["card_id"])}"><h3>{e(c["display_label"])}</h3><p>{e(c["direction_text"])}</p><p>{e(c["confidence_score_text"])}</p><p>{e(c["risk_score_text"])}</p><p>{e(c["next_step_text"])}</p></article>' for c in context.timeframe_cards)
 modules=''.join(f'<article id="{e(c["card_id"])}"><h3>{e(c["display_title"])}</h3><p>{e(c["question_text"])}</p><p>{e(c["summary_text"])}</p></article>' for c in context.module_cards)
 d=context.decision; p=context.progress; h=context.hero; c=context.comparison
 return f'''<!doctype html><html lang="zh-TW"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(context.page_title)}</title><link rel="stylesheet" href="/replay/static/replay_dashboard.css"></head><body><a class="skip" href="#replay-main">跳至主要內容</a><main id="replay-main"><section id="replay-status-banner" aria-live="{e(context.status_banner.get("aria_live","polite"))}">{e(context.status_banner.get("short_text",""))}</section><header id="replay-header"><h1>{e(context.page_title)}</h1><p>{e(context.page_subtitle)}</p></header><section id="replay-hero"><h2>{e(h.get("headline","目前幀無法安全顯示決策"))}</h2></section><section id="replay-progress"><progress value="{e(p.get("progress_value",""))}" max="100" aria-valuenow="{e(p.get("progress_value",""))}" aria-valuemin="0" aria-valuemax="100" aria-valuetext="{e(p.get("percent_text","無法取得"))}"></progress><p>{e(p.get("percent_text","無法取得"))}</p></section><section id="replay-decision"><article id="replay-decision-direction">{e(d.get("direction_text"))}</article><article id="replay-decision-confidence">{e(d.get("confidence_score_text"))}</article><article id="replay-decision-risk">{e(d.get("risk_score_text"))}</article><article id="replay-decision-next-step">{e(d.get("next_step_text"))}</article></section><section id="replay-comparison"><h2>{e(c.get("headline"))}</h2></section><section id="replay-timeframes">{cards}</section><section id="replay-modules">{modules}</section><section id="replay-messages">{''.join(f'<p>{e(x.get("short_text"))}</p>' for x in context.messages)}</section><footer id="replay-footer">{e(context.footer.get("disclaimer_text"))} · WSGI {REPLAY_UI_VERSION}</footer></main></body></html>'''
