"""Typed, read-only presentation model for future Dashboard consumers."""
from __future__ import annotations
from dataclasses import dataclass
from enum import StrEnum
from typing import Mapping
from ..analysis.position_engine import ALL_TIMEFRAMES, PositionTimeframe
from ..decision.decision_contract import DECISION_INPUT_CONTRACT_VERSION, DecisionInputContract
from ..decision.decision_confidence import DECISION_CONFIDENCE_ENGINE_VERSION, DecisionConfidenceResult
from ..decision.risk_engine import RISK_ENGINE_VERSION, RiskResult
from ..decision.next_step_engine import NEXT_STEP_ENGINE_VERSION, NextStepResult
DASHBOARD_READ_MODEL_VERSION="1.0"
class DashboardDisplayState(StrEnum): READY="ready"; OBSERVING="observing"; WAITING="waiting"; REVIEW_REQUIRED="review_required"; BLOCKED="blocked"; MARKET_CLOSED="market_closed"; STALE="stale"; INSUFFICIENT="insufficient"; UNAVAILABLE="unavailable"; INVALID="invalid"; CALCULATION_ERROR="calculation_error"
class DashboardAttentionLevel(StrEnum): NONE="none"; LOW="low"; NORMAL="normal"; HIGH="high"; IMMEDIATE="immediate"; UNAVAILABLE="unavailable"
@dataclass(frozen=True,slots=True)
class DashboardReadModelConfig:
 supported_contract_versions:frozenset[str]=frozenset({DECISION_INPUT_CONTRACT_VERSION}); supported_confidence_versions:frozenset[str]=frozenset({DECISION_CONFIDENCE_ENGINE_VERSION}); supported_risk_versions:frozenset[str]=frozenset({RISK_ENGINE_VERSION}); supported_next_step_versions:frozenset[str]=frozenset({NEXT_STEP_ENGINE_VERSION}); timeframe_order:tuple[PositionTimeframe,...]=ALL_TIMEFRAMES; display_labels:Mapping[PositionTimeframe,str]=None; warning_limit:int=32; secondary_reason_limit:int=3; supporting_factor_limit:int=3; show_raw_state:bool=True; show_source_versions:bool=True; allow_partial_timeframes:bool=True
 def __post_init__(self):
  if not all((self.supported_contract_versions,self.supported_confidence_versions,self.supported_risk_versions,self.supported_next_step_versions)) or tuple(dict.fromkeys(self.timeframe_order))!=ALL_TIMEFRAMES or min(self.warning_limit,self.secondary_reason_limit,self.supporting_factor_limit)<=0:raise ValueError("Dashboard config must contain versions, fixed timeframe order and positive limits.")
  if self.display_labels is None:object.__setattr__(self,"display_labels",{PositionTimeframe.M15:"15m",PositionTimeframe.M60:"60m",PositionTimeframe.D1:"1d",PositionTimeframe.W1:"1w"})
 @classmethod
 def provisional(cls)->"DashboardReadModelConfig":return cls()
@dataclass(frozen=True,slots=True)
class ModuleCardView: module:str; headline:str; state:str; status:str|None; confirmation_state:str|None; quality_state:str|None; short_reason:str|None; raw_state:str|None; warnings:tuple[str,...]; valid:bool
@dataclass(frozen=True,slots=True)
class TimeframeDashboardView: timeframe:PositionTimeframe; display_label:str; display_state:DashboardDisplayState; direction:str; confidence_score:object; confidence_level:str; risk_score:object; risk_level:str; next_step:str; next_step_priority:str; position:ModuleCardView; trend:ModuleCardView; structure:ModuleCardView; timing:ModuleCardView; primary_reason:str|None; warnings:tuple[str,...]; valid:bool
@dataclass(frozen=True,slots=True)
class MarketOverviewView: evaluated_at:object; display_state:DashboardDisplayState; session:str|None; market_phase:str|None; trading_date:object|None; data_freshness:str; usable_timeframe_count:int; valid_timeframe_count:int; warning_count:int; primary_warning:str|None; source_versions:Mapping[str,str]; valid:bool
@dataclass(frozen=True,slots=True)
class MarketDecisionView: direction:str; confidence_score:object; confidence_level:str; confidence_state:str; risk_score:object; risk_level:str; risk_state:str; next_step:str; next_step_state:str; next_step_priority:str; primary_reason:str|None; secondary_reasons:tuple[str,...]; supporting_factors:tuple[str,...]; blockers:tuple[str,...]; display_state:DashboardDisplayState
@dataclass(frozen=True,slots=True)
class ThreeSecondSummary: market_state:str; direction_text:str; confidence_text:str; risk_text:str; next_step_text:str; attention_text:str; display_state:DashboardDisplayState
@dataclass(frozen=True,slots=True)
class DashboardReadModel: version:str; evaluated_at:object; display_state:DashboardDisplayState; attention:DashboardAttentionLevel; market_overview:MarketOverviewView; market_decision:MarketDecisionView; timeframes:Mapping[PositionTimeframe,TimeframeDashboardView]; summary:ThreeSecondSummary; valid:bool; warnings:tuple[str,...]; error_codes:tuple[str,...]
def _invalid(c,code):
 overview=MarketOverviewView(getattr(c,"evaluated_at",None),DashboardDisplayState.INVALID,None,None,None,"invalid",0,0,0,code,{},False);decision=MarketDecisionView("unavailable",None,"invalid","invalid",None,"invalid","invalid","invalid","invalid","critical",code,(),(),(code,),DashboardDisplayState.INVALID);summary=ThreeSecondSummary("無法顯示","—","—","—","資料來源無效","需要處理",DashboardDisplayState.INVALID);return DashboardReadModel(DASHBOARD_READ_MODEL_VERSION,getattr(c,"evaluated_at",None),DashboardDisplayState.INVALID,DashboardAttentionLevel.IMMEDIATE,overview,decision,{},summary,False,(),(code,))
def _card(item):return ModuleCardView(item.module.value,item.normalized_state.value,item.normalized_state.value,item.data_status.value if item.data_status else None,item.confirmation_state.value,None,item.error_code,item.raw_state,item.warnings,item.valid)
def build_dashboard_read_model(contract:DecisionInputContract,confidence:DecisionConfidenceResult,risk:RiskResult,next_step:NextStepResult,config:DashboardReadModelConfig)->DashboardReadModel:
 if not isinstance(contract,DecisionInputContract) or not isinstance(confidence,DecisionConfidenceResult) or not isinstance(risk,RiskResult) or not isinstance(next_step,NextStepResult):raise TypeError("Dashboard sources must use supported types")
 if contract.contract_version not in config.supported_contract_versions or confidence.engine_version not in config.supported_confidence_versions or risk.engine_version not in config.supported_risk_versions or next_step.engine_version not in config.supported_next_step_versions or len({contract.evaluated_at,confidence.evaluated_at,risk.evaluated_at,next_step.evaluated_at})!=1 or getattr(contract.evaluated_at,"tzinfo",None) is None:return _invalid(contract,"source_mismatch")
 state=DashboardDisplayState.INVALID if not risk.valid else DashboardDisplayState.STALE if risk.operational_state.value=="stale" else DashboardDisplayState.BLOCKED if next_step.operational_state.value=="blocked" else DashboardDisplayState.WAITING if next_step.operational_state.value in {"waiting","provisional"} else DashboardDisplayState.OBSERVING
 views={}
 for tf in ALL_TIMEFRAMES:
  f=contract.timeframes[tf]; co=confidence.timeframe_results[tf]; ri=risk.timeframe_risks[tf]; ns=next_step.timeframe_steps[tf]; views[tf]=TimeframeDashboardView(tf,config.display_labels[tf],state,co.direction.value,co.confidence_score,co.confidence_state.value,ri.risk_score,ri.risk_level.value,ns.step_type.value,ns.priority.value,_card(f.position),_card(f.trend),_card(f.structure),_card(f.timing),ns.reason_codes[0].value if ns.reason_codes else None,f.warnings,co.valid)
 warnings=tuple(w for f in contract.timeframes.values() for w in f.warnings)[:config.warning_limit];versions={"contract":contract.contract_version,"confidence":confidence.engine_version,"risk":risk.engine_version,"next_step":next_step.engine_version,"read_model":DASHBOARD_READ_MODEL_VERSION};overview=MarketOverviewView(contract.evaluated_at,state,None,None,None,"stale" if state is DashboardDisplayState.STALE else "available",confidence.usable_timeframe_count,risk.valid_timeframe_count,len(warnings),warnings[0] if warnings else None,versions,state not in {DashboardDisplayState.INVALID,DashboardDisplayState.STALE});decision=MarketDecisionView(confidence.overall_direction.value,confidence.overall_confidence_score,confidence.score_level.value,confidence.overall_confidence_state.value,risk.overall_risk_score,risk.overall_risk_level.value,risk.operational_state.value,next_step.next_step.value,next_step.operational_state.value,next_step.priority.value,next_step.reason_codes[0].value if next_step.reason_codes else None,tuple(x.value for x in next_step.reason_codes[1:config.secondary_reason_limit]),next_step.supporting_factors,tuple(x.value for x in next_step.reason_codes if "conflict" in x.value or "stale" in x.value),state);attention=DashboardAttentionLevel.IMMEDIATE if state in {DashboardDisplayState.INVALID,DashboardDisplayState.STALE} else DashboardAttentionLevel.HIGH if state is DashboardDisplayState.BLOCKED else DashboardAttentionLevel.NORMAL;summary=ThreeSecondSummary(state.value,confidence.overall_direction.value,str(confidence.overall_confidence_score),str(risk.overall_risk_score),next_step.next_step.value,"需要處理" if attention in {DashboardAttentionLevel.IMMEDIATE,DashboardAttentionLevel.HIGH} else "持續觀察",state);return DashboardReadModel(DASHBOARD_READ_MODEL_VERSION,contract.evaluated_at,state,attention,overview,decision,views,summary,state is DashboardDisplayState.OBSERVING,warnings,())
