from kam_market_ai.dashboard import DASHBOARD_PRESENTER_VERSION, DASHBOARD_READ_MODEL_VERSION, DASHBOARD_SERIALIZATION_VERSION, DASHBOARD_UI_VERSION, DASHBOARD_WSGI_ADAPTER_VERSION
from kam_market_ai.dashboard.wsgi_adapter import DEFAULT_FIXTURE_WHITELIST


def test_sprint_three_version_matrix_and_public_exports_are_frozen_at_one():
    assert (DASHBOARD_READ_MODEL_VERSION, DASHBOARD_SERIALIZATION_VERSION, DASHBOARD_PRESENTER_VERSION, DASHBOARD_WSGI_ADAPTER_VERSION, DASHBOARD_UI_VERSION) == ("1.0",) * 5
    assert "stale" in DEFAULT_FIXTURE_WHITELIST and "invalid" in DEFAULT_FIXTURE_WHITELIST
