from test_replay_evaluator_adapter import test_injected_frozen_bundle_evaluates_fixed_engine_slots_deterministically
def test_evaluated_frame_contract_regression(): test_injected_frozen_bundle_evaluates_fixed_engine_slots_deterministically()
